# Generated by Django 4.1.1 on 2022-09-23 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AkumaNoMi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_akuma', models.CharField(max_length=50)),
                ('tipo_akuma', models.CharField(max_length=50)),
                ('descricao_akuma', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_personagem', models.CharField(max_length=50)),
                ('recompensa_personagem', models.CharField(max_length=50)),
                ('tripulacao_personagem', models.CharField(max_length=50)),
                ('descricao_personagem', models.TextField()),
                ('foto', models.ImageField(upload_to='')),
                ('akumaNoMi_personagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ships.akumanomi')),
            ],
        ),
    ]
