# Generated by Django 4.1.1 on 2022-09-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_personagem', models.CharField(max_length=50)),
                ('recompensa_personagem', models.FloatField()),
                ('tripulacao_personagem', models.CharField(max_length=50)),
                ('akumaNoMi_personagem', models.CharField(max_length=50)),
            ],
        ),
    ]
