# Generated by Django 4.1.1 on 2022-09-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkumaNoMi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_akuma', models.CharField(max_length=50)),
                ('tipo_akuma', models.CharField(max_length=50)),
                ('descricao_akuma', models.TextField()),
                ('foto_akuma', models.ImageField(upload_to='')),
            ],
        ),
    ]
