# Generated by Django 4.1.1 on 2022-09-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='descricao_personagem',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
