# Generated by Django 4.1.1 on 2022-09-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='akumaNoMi_personagem',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='AkumaNoMi',
        ),
    ]
