# Generated by Django 4.1.1 on 2022-09-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0002_characters_descricao_personagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='recompensa_personagem',
            field=models.CharField(max_length=50),
        ),
    ]
