# Generated by Django 4.1.1 on 2022-09-23 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0002_akumanomi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='akumaNoMi_personagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ships.akumanomi'),
        ),
    ]
