# Generated by Django 4.1.1 on 2022-09-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0003_alter_characters_akumanomi_personagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='akumaNoMi_personagem',
            field=models.CharField(max_length=50),
        ),
    ]
