# Generated by Django 4.1.1 on 2022-09-26 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0011_alter_characters_akumanomi_personagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='akumaNoMi_personagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ships.akumanomi'),
        ),
    ]
